# benchmark config yaml
### Please fill these accordingly
data_dir: /mnt/weka/tpcx-bb/sf1000/parquet_3gb/
output_dir: ./
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file_path: /home/nicholasb/dask-local-directory/scheduler.json
dask_profile: False
dask_dir: ./
32GB_workers: 8

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF1000 Benchmarking Matrix
get_read_time: False
