# benchmark config yaml
### Please fill these accordingly
data_dir: /tpcx-bb/sf30000/
output_dir: ./
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file: /root/dask-local-directory/dask-scheduler.json
dask_profile: False
dask_dir: ./
32GB_workers: 8

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF30000 Benchmarking Matrix
get_read_time: False
