# benchmark config yaml
### Please fill these accordingly
data_dir: 
output_dir: ./
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

cluster_host: 
cluster_port: 8786
dask_profile: False
dask_dir: ./
32GB_workers: 16

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF1000 Benchmarking Matrix
get_read_time: False
