# benchmark config yaml
### Please fill these accordingly
data_dir: /tpcx-bb/sf1000/parquet_3gb_test/
output_dir: /tpcx-bb/sf1000/results/
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file: /root/dask-local-directory/scheduler.json
dask_profile: False
dask_dir: ./
40GB_workers: 8

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF1000 Benchmarking Matrix
get_read_time: False
